# Generated by Django 2.1.15 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=200)),
                ('LocalSMSPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GPRSPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OffNetPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IrishLandlinePricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InternationalCallPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InternationalSMSPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OnNetPricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
        migrations.AlterUniqueTogether(
            name='daily_usage',
            unique_together={('phonenumber', 'date')},
        ),
    ]
