# Generated by Django 2.1.15 on 2024-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='GPRSPricing',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
