# Generated by Django 2.1.15 on 2024-03-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20240320_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Abdd',
            new_name='phone_number',
        ),
    ]
